name: Lint
permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-python@v2
      - uses: psf/black@8a737e727ac5ab2f1d4cf5876720ed276dc8dc4b # 25.1.0
        with:
          options: "--check"
          src: "."
      - name: docstrings
        run: |
          pip install flit
          pushd $(mktemp -d)
          git clone https://github.com/Carreau/velin.git --single-branch --depth 1
          cd velin
          flit install
          popd
          velin . --check
